### ISSUE TITLE
Fresh node fails to start: Failed to register FetchError request to http://localhost:10365/requirements failed

### ISSUE THREAD

**Issue by typoworx-de** [filecoin-saturn/L1-node#104]
My new node fails with this error in docker:
node-"main" Failed to register FetchError request to http://localhost:10365/requirements failed, reason: connect ECONNREFUSED 127.0.0.1:10365

Ports 80/443 are exposed as mentioned port requirements in the docs.

**Comment by DiegoRBaquero** [comment]
You should run the built docker images. It seems like you are trying to dev version, which would require running the orchestrator too, but it is not public.

**Comment by typoworx-de** [comment]
@DiegoRBaquero thanks for reply. I'm using this image/version:
ghcr.io/filecoin-saturn/l1-node:main

Is the manual build mandatory to get in running or is there a final main-net image?

**Comment by typoworx-de** [comment]
@DiegoRBaquero please re-open as already stated I'm not building the dev version nor using self-built image. So your assumption I've been using the wrong image or a dev-version is wrong!

this is my docker-compose.yml
```yaml
version: '3.5'

volumes:
  filecoin-saturn-node-storage:
    external: true
    name: filecoin-saturn-node-storage

  filecoin-saturn-node:
    # Read this for Filecoin-Saturn Token
    # https://strn.network/#setupyournode
    # https://github.com/filecoin-saturn/L1-node#set-up-a-node
    image: ghcr.io/filecoin-saturn/l1-node:main
    container_name: filecoin-saturn
    restart: unless-stopped
    volumes:
      - filecoin-saturn-node-storage:/usr/src/app/shared
    ports:
      - 80:80/tcp
      - 443:443/tcp
    ulimits:
      nofile:
        soft: "1000000"
        hard: "1000000"
    environment:
      - SATURN_NETWORK="main"
      - NODE_OPERATOR_EMAIL="${NODE_EMAIL}"
      - FIL_WALLET_ADDRESS="${WALLET_FIL}"
```
