### ISSUE TITLE
Trying to deploy using docker-compose and crash due to SIGCHLD Error in NGINX?!

### ISSUE THREAD

**Issue by typoworx-de** [filecoin-saturn/L1-node#107]
My docker-compose.yml is as follows. After starting it (testing on normal docker, not swarm) I'm getting this error:

```
filecoin-saturn1        | 2022-11-14T15:02:32.111Z node-"main":server shim process running
filecoin-saturn1        | 2022-11-14T15:02:32.610Z node-"main":log-ingestor Reading nginx log file
filecoin-saturn1        | 2022/11/14 15:03:31 [notice] 43#43: http file cache: /usr/src/app/shared/nginx_cache 0.000M, bsize: 4096
filecoin-saturn1        | 2022/11/14 15:03:32 [notice] 28#28: signal 17 (SIGCHLD) received from 43
filecoin-saturn1        | 2022/11/14 15:03:32 [notice] 28#28: cache loader process 43 exited with code 0
filecoin-saturn1        | 2022/11/14 15:03:32 [notice] 28#28: signal 29 (SIGIO) received
```

environment:
NODE_EMAIL and WALLET_FIL are set using docker-env.

```yaml
version: '3.5'

volumes:
  filecoin-saturn-node-storage:
    external: true
    name: filecoin-saturn-node-storage

  filecoin-saturn-node:
    # Read this for Filecoin-Saturn Token
    # https://strn.network/#setupyournode
    # https://github.com/filecoin-saturn/L1-node#set-up-a-node
    image: ghcr.io/filecoin-saturn/l1-node:main
    container_name: filecoin-saturn
    restart: unless-stopped
    volumes:
      - filecoin-saturn-node-storage:/usr/src/app/shared
    ports:
      - 80:80/tcp
      - 443:443/tcp
    ulimits:
      nofile:
        soft: "1000000"
        hard: "1000000"
    environment:
      - SATURN_NETWORK="main"
      - ORCHESTRATOR_REGISTRATION="true"
      - IPFS_GATEWAY_ORIGIN="https://ipfs.io"
      - NODE_OPERATOR_EMAIL="${NODE_EMAIL}"
      - FIL_WALLET_ADDRESS="${WALLET_FIL}"
```
