### ISSUE TITLE
Replace update.sh with an external dependency

### ISSUE THREAD

**Issue by joaosa** [filecoin-saturn/L1-node#109]
The less code we have to maintain, the less complexity we have to focus on and the better it will be on the long run.

This principle can be applied to `update.sh` which can be replaced by [watchtower](https://github.com/containrrr/watchtower), for instance.

Since we can't have all nodes rebooting at the same time, as that would kill the network, we can use [lifecycle hooks](https://containrrr.dev/watchtower/lifecycle-hooks/) to wait a random time, as it is currently done [here](https://github.com/filecoin-saturn/L1-node/blob/main/update.sh#L49).

[This guide](https://containrrr.dev/watchtower/usage-overview/) offers a good way to get started. [This](https://www.digitalocean.com/community/tutorials/how-to-automatically-update-docker-container-images-with-watchtower-on-ubuntu-22-04) is another good ref.

One should note that watchtower [does not support rollbacks](https://github.com/containrrr/watchtower/issues/90). Doing so would be ideal, as per [this issue](https://github.com/filecoin-saturn/L1-node/issues/32).

**Comment by vorburger** [comment]
> One should note that watchtower https://github.com/containrrr/watchtower/issues/90. Doing so would be ideal, as per https://github.com/filecoin-saturn/L1-node/issues/32.

I think that is an "orthogonal" issue - you probably (I haven't tried it) COULD already replace the `update.sh` script "as-is" with Watchtower, and just [`--stop-timeout 900`](https://containrrr.dev/watchtower/arguments/#wait_until_timeout), to replicate [this](https://github.com/filecoin-saturn/L1-node/blob/5baf03497c2a708c77779c99d6ba0c3b0af9d479/update.sh#L55)...

... and then, in a future next step, you (probably, TBD) can somehow get Watchtower to attempt a "roling update", perhaps with [this](https://containrrr.dev/watchtower/arguments/#rolling_restart) and/or [this](https://containrrr.dev/watchtower/running-multiple-instances/)? (Their doc isn't clear if and how exactly they support it, at least to me.) But perhaps this would be easier if the container first had #124 and #125?

**Comment by joaosa** [comment]
> > One should note that watchtower [containrrr/watchtower#90](https://github.com/containrrr/watchtower/issues/90). Doing so would be ideal, as per #32.
> 
> I think that is an "orthogonal" issue - you probably (I haven't tried it) COULD already replace the `update.sh` script "as-is" with Watchtower, and just [`--stop-timeout 900`](https://containrrr.dev/watchtower/arguments/#wait_until_timeout), to replicate [this](https://github.com/filecoin-saturn/L1-node/blob/5baf03497c2a708c77779c99d6ba0c3b0af9d479/update.sh#L55)...
> 
yeah you're absolutely right! These are orthogonal issues.

> ... and then, in a future next step, you (probably, TBD) can somehow get Watchtower to attempt a "roling update", perhaps with [this](https://containrrr.dev/watchtower/arguments/#rolling_restart) and/or [this](https://containrrr.dev/watchtower/running-multiple-instances/)? (Their doc isn't clear if and how exactly they support it, at least to me.) But perhaps this would be easier if the container first had #124 and #125?

that sounds like a good approach. thank you for looking it up :)

**Comment by AnomalRoil** [comment]
FYI, I've successfully setup my node with automatic updates through Watchtower using the following docker-compose.yml file:
```
version: "3.8"
services:
  saturn-node:
    image: ghcr.io/filecoin-saturn/l1-node:main
    container_name: saturn_node
    restart: always
    environment:
      SATURN_NETWORK: "main"
      FIL_WALLET_ADDRESS: "YOUR FIL ADDRESS"
      NODE_OPERATOR_EMAIL: "YOUR EMAIL"
      SPEEDTEST_SERVER_CONFIG: "--server-id=ID OF THE CLOSEST SPEEDTEST SERVER"
    ulimits:
        nofile:
          soft: 65536
          hard: 65536
    ports:
      - 80:80
      - 443:443
    network_mode: host
    stop_signal: SIGTERM
    stop_grace_period: 30m
    labels:
      com.centurylinklabs.watchtower.lifecycle.pre-update-timeout: 30
      com.centurylinklabs.watchtower.lifecycle.post-update-timeout: 30
    volumes:
      - saturn_data:/usr/src/app/shared

  watchtower:
      image: containrrr/watchtower
      environment:
        WATCHTOWER_POLL_INTERVAL: 10800
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

volumes:
  saturn_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/srv/saturn-data'
```
